#fos_user:
    #resource: "@FOSUserBundle/Resources/config/routing/all.xml"
# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
    path: /iniciar-sesion
    controller: fos_user.security.controller:loginAction

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /perfil

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /registro

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /recuperar-clave

fos_user_resetting_request:
    path: /recuperar-clave
    controller: fos_user.resetting.controller:requestAction 

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /perfil

fos_user_profile_edit:
    path: /editar-perfil
    controller: fos_user.profile.controller:editAction 





