vich_uploader:
    db_driver: orm

    mappings:
        mascota_image:
            uri_prefix: /images/mascotas
            upload_destination: '%kernel.project_dir%/public/images/mascotas'
            
            inject_on_load: false
        
            