vich_uploader:
    db_driver: orm

    mappings:
        mascota_image:
            uri_prefix: /images/mascotas
            upload_destination: '%kernel.project_dir%/public/images/mascotas'
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        user_imagen:
            uri_prefix: /images/user
            upload_destination: '%kernel.project_dir%/public/images/user'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
        paquete_image:
            uri_prefix: /images/paquete
            upload_destination: '%kernel.project_dir%/public/images/paquete'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        
            